export const easy = [
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
];

export const medium = [
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍍", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🥭", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍍", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🥭", fliped: false },
];

export const hard = [
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍍", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🥭", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍎", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍓", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍇", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍈", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍉", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍊", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍋", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍌", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍍", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🥭", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍎", fliped: false },
  { id: Math.ceil(Math.random() * 1000000), content: "🍓", fliped: false },
];
